version: "3"
services:
  frontend:
    build:
      context: ./react-app
    image: react-app
    container_name: react-app
    ports:
      - "5000:5000"
    environment:
      - VITE_APP_PORT=5000
    networks:
      - microservice_public
  backend:
    build:
      context: ./express-app
    image: express-app
    container_name: express-app
    ports:
      - "9000:9000"
    environment:
      - APP_PORT=9000
    networks:
      - microservice_public
networks:
  microservice_public:
    driver: bridge
  microservice_private:
    driver: none