version: "3"
services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./react-app
    image: react-app
    container_name: react-app
    ports:
      - "5000:5000"
    environment:
      - VITE_APP_PORT=5000
      - VITE_EXPRESS_BE_URL=http://backend:9000
    networks:
      - private
      - public
  backend:
    build:
      context: ./express-app
    image: express-app
    container_name: express-app
    environment:
      - APP_PORT=9000
    networks:
      - private
    expose:
      - 9000
    # ports:
    #   - "9000:9000"
networks:
  public:
    driver: bridge
  private:
    driver: bridge
    internal: true